version: "3.8"

services:
  traefik:
    image: traefik:v3.1
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - /srv/docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /srv/docker/traefik/dynamic:/etc/traefik/dynamic:ro
      - /srv/docker/traefik/acme.json:/acme.json
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    networks:
      - internal
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    networks:
      - internal
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  adguard:
    image: adguard/adguardhome:latest
    networks:
      - internal
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 80
        published: 8080
        protocol: tcp
    volumes:
      - /srv/docker/adguard/data/work:/opt/adguardhome/work
      - /srv/docker/adguard/data/conf:/opt/adguardhome/conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  whoami:
    image: traefik/whoami
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints:
          - node.role == manager

networks:
  internal:
    external: true
